# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WineClubChallenge' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WineClubChallenge

	pod 'AFNetworking'
	pod 'Masonry'

  target 'WineClubChallengeTests' do
    inherit! :search_paths
    # Pods for testing

  end

end
